config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope :user do
    get 'users/', to: 'devise/registrations#new'
    get 'users/password', to: 'devise/passwords#new'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  get 'home/about'
  get 'posts/myposts'
  get 'profiles/index'
  resources :posts
  resources :comments
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
  resources :likes, only: [:create, :destroy]

  post 'users/:id/follow', to: 'users#follow', as: 'follow'
  post 'users/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'users/:id/accept', to: 'users#accept', as: 'accept'
  post 'users/:id/decline', to: 'users#decline', as: 'decline'
  post 'users/:id/cancel', to: 'users#cancel', as: 'cancel'

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'posts#index'
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

## frozen_string_literal: true

# This is the ProfilesController.
class ProfilesController < ApplicationController
  def index
    @users = users
  end

  def users
    query = User.ransack(username_cont: search_query)
    @users = query.result(distince: true)
  end

  def search_query
    params[:query]
  end
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

# This module contains helper methods for the ProfilesController.
# It can be used to provide additional functionality or formatting for profile-related views.
module ProfilesHelper
end

app/views/profiles/index.html.erb
<% if @users.any? %>
  <div class="user-grid">
    <% @users.each do |user| %>
      <div class="user-card">
        <div class="avatar-container">
          <%= link_to user_path(user) do %>
            <% if user.avatar.attached? %>
              <%= image_tag user.avatar, alt: user.username, class: "avatar-img" %>
            <% else %>
              <%= image_tag 'default_avatar.png', alt: 'Default Profile', class: "avatar-img" %>
            <% end %>
          <% end %>
        </div>
        <div class="user-info">
          <%= link_to user.username, user_path(user), class: "username-link" %>
          <p class="email"><%= user.email %></p>
          <% if user.bio.present? %>
            <p class="bio"><%= truncate(user.bio, length: 100) %></p>
          <% end %>

          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= button_to "Unfollow", unfollow_path(user), method: :post, class: "btn btn-danger btn-sm mt-2" %>
            <% elsif current_user.sent_follow_request_to?(user) %>
              <%= button_to "Cancel follow request", cancel_path(user), method: :post, class: "btn btn-warning btn-sm mt-2" %>
            <% else %>
              <%= button_to "Follow", follow_path(user), method: :post, class: "btn btn-primary btn-sm mt-2" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="no-users-found">
    <p>No users found 😕</p>
  </div>
<% end %>