config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope :user do
    get 'users/', to: 'devise/registrations#new'
    get 'users/password', to: 'devise/passwords#new'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  get 'home/about'
  get 'posts/myposts'
  get 'profiles/index'
  resources :posts
  resources :comments
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
  resources :likes, only: [:create, :destroy]

  post 'users/:id/follow', to: 'users#follow', as: 'follow'
  post 'users/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'users/:id/accept', to: 'users#accept', as: 'accept'
  post 'users/:id/decline', to: 'users#decline', as: 'decline'
  post 'users/:id/cancel', to: 'users#cancel', as: 'cancel'

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'posts#index'
end

app/views/layouts/_footer.html.erb
<footer class="bg-light border-top py-3">
  <div class="container text-center text-muted small">
    <div class="row justify-content-center">
      <div class="col-md-3 col-6">
        <h6 class="text-dark mb-1">Instaclone</h6>
        <p class="mb-2">Instagram, but made by Indians.</p>
      </div>
      <div class="col-md-3 col-6">
        <h6 class="text-dark mb-1">Links</h6>
        <ul class="list-unstyled mb-2">
          <li><a href="#" class="text-muted text-decoration-none">About</a></li>
          <li><a href="#" class="text-muted text-decoration-none">Help</a></li>
          <li><a href="#" class="text-muted text-decoration-none">Privacy</a></li>
          <li><a href="#" class="text-muted text-decoration-none">Terms</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-12">
        <h6 class="text-dark mb-1">Thanks</h6>
        <p class="mb-2">For paying attention to this piece of art.</p>
      </div>
    </div>
    <div class="mt-2">
      <small>&copy; 2025 Instaclone</small>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
</head>
<body>
<% if user_signed_in? %>
  <nav class="navbar navbar-light bg-light d-flex justify-content-between align-items-center px-3 position-relative" style="height: 70px;">
    <% if current_user.avatar.attached? %>
      <li class="navbar-avatar-item d-flex flex-column align-items-center" style="list-style: none;">
        <%= image_tag current_user.avatar, class: 'rounded-circle avatar-hover', style: 'width: 50px; height: 50px;' %>
        <span class="navbar-username">
          <%= current_user.username %>
        </span>
      </li>
    <% else %>
    <li class="navbar-avatar-item d-flex flex-column align-items-center" style="list-style: none;">
        <%= image_tag "default_avatar.png", class: 'rounded-circle avatar-hover', style: 'width: 50px; height: 50px;' %>
        <span class="navbar-username">
          <%= current_user.username %>
        </span>
      </li>
    <% end %>
<% else %>
  <nav class="navbar navbar-light bg-light d-flex justify-content-between align-items-center px-3 position-relative" style="height: 70px;">
  <div style="width: 50px; height: 50px;"></div>
<% end %>

  <!-- Centered Home link -->
  <a class="navbar-brand mx-auto text-center font-weight-bold" href="/">Instaclone</a>

  <!-- Search field -->
  <div class="d-flex align-items-center" style="position: absolute; margin-left: 100px;">
  <%= form_with url: profiles_index_path, method: :get, local: true, html: { class: 'd-flex align-items-center', style: 'width: 200px;' } do |form| %>
    <%= form.search_field :query, value: params[:query], placeholder: 'Search', aria: { label: 'Search' }, class: 'search-input', style: 'width: 100%;' %>
  <% end %>
</div>

  <!-- Menu toggle button and menu -->
  <div class="d-flex align-items-start position-relative">
    <button class="navbar-toggler" id="menuToggleBtn" type="button" aria-label="Toggle menu">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse position-absolute" id="navbarSupportedContent_unique" style="top: 40px; right: 0; min-width: 200px; z-index: 1050;">
      <ul class="navbar-nav flex-column bg-white border rounded shadow p-2">
        <li class="nav-item">
          <%= link_to 'Upload Post', new_post_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'View My Profile', current_user, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Posts', posts_myposts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link', style:"border:none;" %>
          </li>
          <li class="nav-item">
          <% if current_user.admin? %>
            <%= link_to 'Admin Dashboard', rails_admin_path, class: 'nav-link' %>
          <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link', style:"border:none;" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'About Page', home_about_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- JS Scripts -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<script>
  $(document).ready(function () {
    const $toggleBtn = $('#menuToggleBtn');
    const $menu = $('#navbarSupportedContent_unique');

    $toggleBtn.on('click', function (e) {
      e.stopPropagation(); // prevent immediate document close
      $menu.collapse('toggle');
    });

    // Hide menu when clicking outside
    $(document).on('click', function (e) {
      if (!$(e.target).closest('#navbarSupportedContent_unique, #menuToggleBtn').length) {
        $menu.collapse('hide');
      }
    });
  });
</script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
    crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <div class="d-flex flex-column flex-grow-1">
      <%= render "layouts/navbar" %>
      <main class="flex-grow-1">
        <%= yield %>
      </main>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>